Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.hostname = 'nginx.devops.com'
    web.vm.box = "debian/jessie64"

    web.vm.network :private_network, ip: "10.127.0.10"
    web.vm.network "forwarded_port", guest: 80, host: 8181
    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "web"]
    end

    web.vm.provision "shell" do |s|
	s.path = "provision/web/setup.sh"
    end
  end

  config.vm.define "php" do |php|
    php.vm.hostname = 'php.devops.com'
    php.vm.box = "debian/jessie64"

    php.vm.network :private_network, ip: "10.127.0.20"

    php.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "php"]
    end

    php.vm.provision "shell" do |s|
       s.path = "provision/php/setup.sh"
    end
  end
  
  config.vm.define "redis" do |redis|
    redis.vm.hostname = 'redis.devops.com'
    redis.vm.box = "debian/jessie64"

    redis.vm.network :private_network, ip: "10.127.0.30"
    
    
    redis.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 256]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "redis"]
    end
    redis.vm.provision "shell" do |s|
      s. path = "provision/redis/setup.sh"
    end
  end 
	
end
